cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    '139082132':
      email: 139082132@gmail.com
      name: user_139082132
      password: $2b$12$T76R9LmVPd6Z42WJC8ANTOTQqyjO4jQHczMpZ03SbaBw0PDqE3RsG
    '895523414':
      email: 895523414@gmail.com
      name: user_895523414
      password: $2b$12$ay6u1aVRkrpkh2F3shSEYuL6ix/NSZSAdrDIT/PDUa6YUSs2OoN5C
preauthorized: {}
